use TechShop;
go

--1) Write an SQL query to find out which customers have not placed any orders.
select firstName+' '+lastName as [Customer Name] from Customers
except select customerID from Orders;

--2) Write an SQL query to find the total number of products available for sale.
select sum(quantity) as [Total number of products] from OrderDetails;

--3) Write an SQL query to calculate the total revenue generated by TechShop.
select sum(totalAmount) as totalRevenue from Orders
where orderID in (select orderID from OrderDetails);

--4) Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter.
declare @productName varchar(20) = 'smartwatch';

select avg(quantity) as [average of entered product] from OrderDetails 
where productID in (
select productID from Products
where productName = @productName
);

--5) Write an SQL query to calculate the total revenue generated by a specific customer. Allow users to input the customer ID as a parameter.
declare @customerID int = 106;

select sum(totalAmount) as [Total Revenue] from Orders
where orderID in (select orderID
from Orders where customerID = @customerID
)


--6) Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed
insert into Orders values(12,106,'2025-03-24',17500);                           --inserted one more value to check


select top 1 c.firstName+' '+c.lastName as customerName, count(o.orderID) as ordersPlaced from Customers c
join Orders o
on c.customerID = o.customerID
group by firstName,lastName
order by count(o.orderID) desc;


--7) Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders.
select top 1 p.productName, sum(od.quantity) as totalQuantity from Products p
join OrderDetails od
on p.productID = od.productID
group by productName
order by totalQuantity desc;

--8) Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending.
select c.firstName+' '+c.lastName as [Customer Name], o.totalAmount
from Customers c 
join Orders o
on c.customerID = o.customerID
where o.totalAmount = (select top 1 sum(totalAmount) from Orders
group by customerID
order by sum(totalAmount) desc);

--9) Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers.
select avg(totalAmount) as Average from Orders;

--10) Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count.

select c.firstName + ' ' + c.lastName as customerName,
(select count(*) from Orders o where o.customerID = c.customerID) as orderCount
from Customers c
order by orderCount desc;


----------------------------------------------
----------------------------------------------

select * from OrderDetails;
select * from Orders;
select * from Products;
select * from Customers;
select * from Inventory;